Update filename-checker.yml

diff --git a/.github/workflows/filename-checker.yml b/.github/workflows/filename-checker.yml
--- a/.github/workflows/filename-checker.yml
+++ b/.github/workflows/filename-checker.yml
@@ -19,6 +19,7 @@ jobs:
         for file in $(git diff --name-only HEAD^..HEAD)
         do
           if [[ $file =~ [^a-z0-9_\-./] ]]; then
-            echo "::error file=$file::File name contains invalid characters"
+            echo "File name contains invalid characters: $file"
+            exit 1
           fi
         done
